### ISSUE TITLE
Feature: cache step

### ISSUE THREAD

**Issue by adrienaury** [c4s4/neon#11]
Bonjour,

Très bel outil, bien pensé et ultra personalisable.

Avez-vous pensé à ajouter une fonctionnalité de caching de la date de modification (ou d'un hash) des entrants d'une target, afin d'éviter de recalculer une étape si cela n'est pas nécessaire ? (comme le fait Make)

Cela pourrait prendre la forme suivante avec un paramètre `uses` sur la target:

```yaml
  build:
    doc: Build binary for current platform
    depends: version
    uses: ["**/*.go"]
    steps:
      - ...
```

Output 

```console
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- build --
Inputs didn't change, skipping
```

**Comment by c4s4** [comment]
Bonjour,

Merci pour votre commentaire. Pour adresser ce besoin, j'ai ajouté une clause `unless` aux targets, qui est une expression qui doit renvoyer un booléen. Si cette expression renvoie `true` alors la target n'est pas exécutée.

Dans l'exemple que vous donnez, on pourrait écrire :

```yaml
build:
  doc: Build binary for current platform
  depends: version
  unless: newer("build/binary", find(".", "**/*.go"))
  steps:
  - ...
```

Ce qui pourrait se traduire en français par : _compiler les sources Go sauf si le binaire est plus récent que chacun des sources_. C'est implémenté dans la release *1.5.0*.

À noter que Go gère nativement, dans ses dernières versions, un cache pour les binaires qu'il génère. Il ne recompile donc que ce qui est nécessaire. On peut nettoyer ce cache avec `go clean -cache`. L'utilisation de `unless` dans ce cas n'est donc pas recommandable. 

*Enjoy!*
