### ISSUE TITLE
Error checking task args for mixed lists

### ISSUE THREAD

**Issue by mitchmieuxplacer** [c4s4/neon#2]
Type is checked on the first element of the list only.

```yaml
default: bug

targets:

  bug:
    steps:
    - $: ['ls', 1]
```
