### ISSUE TITLE
Can't acces map elements

### ISSUE THREAD

**Issue by mitchmieuxplacer** [c4s4/neon#3]
We can't access maps:

```yaml
default: test

properties:
  MAP:
    'foo': 1
    'bar': 2

targets:

  test:
    steps:
    - print: 'foo: ={MAP["foo"]}'
```
