### ISSUE TITLE
Bad error message when parent target not found calling super

### ISSUE THREAD

**Issue by c4s4** [c4s4/neon#4]
For instance with this build file:

```yaml
default: bug

targets:

  bug:
    steps:
    - super:
```
