### ISSUE TITLE
Bad super after call

### ISSUE THREAD

**Issue by c4s4** [c4s4/neon#5]
When calling super after a call, super target is wrong:

```yaml
default: test

targets:

  foo:
    steps:
    - print: "Foo"

  test:
    steps:
    - call: foo
    - super:
```
