### ISSUE TITLE
Repository not found on Windows

### ISSUE THREAD

**Issue by mitchmieuxplacer** [c4s4/neon#7]
Following build file (generated with *c4s4/build/slides.yml* template):

```yaml
extends:
- c4s4/build/slides.yml

properties:
  TITLE:   "Slides"
```

Doesn't work on Windows with following error message:

```
ERROR loading parent build file 'c4s4/build/slides.yml': loading build file '~\.neon\c4s4\build\slides.yml': reading file '~\.neon\c4s4\build\slides.yml': open ~\.neon\c4s4\build\slides.yml: The system cannot find the path specified.
```
